/*  Copyright (C) Bitstem GmbH
 *  All rights reserved.
 *
 *  This source code is proprietary and confidential.
 *  Unauthorized copying, distribution, or disclosure of this file,
 *  in whole or in part, is strictly prohibited unless explicitly
 *  permitted in writing by Bitstem GmbH.
 *
 *  Author: Klaus Kuehnhammer <klaus@bitstem.com>
 */

// GENERATED by tools/gen_rfc6330_kprime_table.py — do not edit by hand.
// Regenerate with `python3 tools/gen_rfc6330_kprime_table.py` after
// updating tests/vectors/rfc6330.txt.
//
// RFC 6330 §5.6 Table 2 — K' values, the supported source-block
// extended source-symbol counts. RFC 6330 §4.3 (Example Parameter
// Derivation Algorithm) needs these to compute KL(n), the maximum
// K' that fits the working-memory bound at sub-block count n.
// Encoder/decoder also use them to round K up to K' per §5.3.1 —
// that's the codec's concern, this header serves the partitioner.
//
// SHA-256 of the source RFC text:    87f6da89cc325987cb2910d1c124f74eaeac5c86a83f962cf347c0cc66321ace
// SHA-256 of the comma-joined K's:   91be16f5af6c040158a4b2813df5471af695134c93feab4a42dadada742716fe

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace LibFlute::rfc6330 {

inline constexpr std::size_t kKPrimeCount = 477;

// Strictly increasing in the range [10, 56403].
inline constexpr std::array<std::uint32_t, kKPrimeCount> kKPrimeTable = {{
    10u, 12u, 18u, 20u, 26u, 30u, 32u, 36u,
    42u, 46u, 48u, 49u, 55u, 60u, 62u, 69u,
    75u, 84u, 88u, 91u, 95u, 97u, 101u, 114u,
    119u, 125u, 127u, 138u, 140u, 149u, 153u, 160u,
    166u, 168u, 179u, 181u, 185u, 187u, 200u, 213u,
    217u, 225u, 236u, 242u, 248u, 257u, 263u, 269u,
    280u, 295u, 301u, 305u, 324u, 337u, 341u, 347u,
    355u, 362u, 368u, 372u, 380u, 385u, 393u, 405u,
    418u, 428u, 434u, 447u, 453u, 466u, 478u, 486u,
    491u, 497u, 511u, 526u, 532u, 542u, 549u, 557u,
    563u, 573u, 580u, 588u, 594u, 600u, 606u, 619u,
    633u, 640u, 648u, 666u, 675u, 685u, 693u, 703u,
    718u, 728u, 736u, 747u, 759u, 778u, 792u, 802u,
    811u, 821u, 835u, 845u, 860u, 870u, 891u, 903u,
    913u, 926u, 938u, 950u, 963u, 977u, 989u, 1002u,
    1020u, 1032u, 1050u, 1074u, 1085u, 1099u, 1111u, 1136u,
    1152u, 1169u, 1183u, 1205u, 1220u, 1236u, 1255u, 1269u,
    1285u, 1306u, 1347u, 1361u, 1389u, 1404u, 1420u, 1436u,
    1461u, 1477u, 1502u, 1522u, 1539u, 1561u, 1579u, 1600u,
    1616u, 1649u, 1673u, 1698u, 1716u, 1734u, 1759u, 1777u,
    1800u, 1824u, 1844u, 1863u, 1887u, 1906u, 1926u, 1954u,
    1979u, 2005u, 2040u, 2070u, 2103u, 2125u, 2152u, 2195u,
    2217u, 2247u, 2278u, 2315u, 2339u, 2367u, 2392u, 2416u,
    2447u, 2473u, 2502u, 2528u, 2565u, 2601u, 2640u, 2668u,
    2701u, 2737u, 2772u, 2802u, 2831u, 2875u, 2906u, 2938u,
    2979u, 3015u, 3056u, 3101u, 3151u, 3186u, 3224u, 3265u,
    3299u, 3344u, 3387u, 3423u, 3466u, 3502u, 3539u, 3579u,
    3616u, 3658u, 3697u, 3751u, 3792u, 3840u, 3883u, 3924u,
    3970u, 4015u, 4069u, 4112u, 4165u, 4207u, 4252u, 4318u,
    4365u, 4418u, 4468u, 4513u, 4567u, 4626u, 4681u, 4731u,
    4780u, 4838u, 4901u, 4954u, 5008u, 5063u, 5116u, 5172u,
    5225u, 5279u, 5334u, 5391u, 5449u, 5506u, 5566u, 5637u,
    5694u, 5763u, 5823u, 5896u, 5975u, 6039u, 6102u, 6169u,
    6233u, 6296u, 6363u, 6427u, 6518u, 6589u, 6655u, 6730u,
    6799u, 6878u, 6956u, 7033u, 7108u, 7185u, 7281u, 7360u,
    7445u, 7520u, 7596u, 7675u, 7770u, 7855u, 7935u, 8030u,
    8111u, 8194u, 8290u, 8377u, 8474u, 8559u, 8654u, 8744u,
    8837u, 8928u, 9019u, 9111u, 9206u, 9303u, 9400u, 9497u,
    9601u, 9708u, 9813u, 9916u, 10017u, 10120u, 10241u, 10351u,
    10458u, 10567u, 10676u, 10787u, 10899u, 11015u, 11130u, 11245u,
    11358u, 11475u, 11590u, 11711u, 11829u, 11956u, 12087u, 12208u,
    12333u, 12460u, 12593u, 12726u, 12857u, 13002u, 13143u, 13284u,
    13417u, 13558u, 13695u, 13833u, 13974u, 14115u, 14272u, 14415u,
    14560u, 14713u, 14862u, 15011u, 15170u, 15325u, 15496u, 15651u,
    15808u, 15977u, 16161u, 16336u, 16505u, 16674u, 16851u, 17024u,
    17195u, 17376u, 17559u, 17742u, 17929u, 18116u, 18309u, 18503u,
    18694u, 18909u, 19126u, 19325u, 19539u, 19740u, 19939u, 20152u,
    20355u, 20564u, 20778u, 20988u, 21199u, 21412u, 21629u, 21852u,
    22073u, 22301u, 22536u, 22779u, 23010u, 23252u, 23491u, 23730u,
    23971u, 24215u, 24476u, 24721u, 24976u, 25230u, 25493u, 25756u,
    26022u, 26291u, 26566u, 26838u, 27111u, 27392u, 27682u, 27959u,
    28248u, 28548u, 28845u, 29138u, 29434u, 29731u, 30037u, 30346u,
    30654u, 30974u, 31285u, 31605u, 31948u, 32272u, 32601u, 32932u,
    33282u, 33623u, 33961u, 34302u, 34654u, 35031u, 35395u, 35750u,
    36112u, 36479u, 36849u, 37227u, 37606u, 37992u, 38385u, 38787u,
    39176u, 39576u, 39980u, 40398u, 40816u, 41226u, 41641u, 42067u,
    42490u, 42916u, 43388u, 43840u, 44279u, 44729u, 45183u, 45638u,
    46104u, 46574u, 47047u, 47523u, 48007u, 48489u, 48976u, 49470u,
    49978u, 50511u, 51017u, 51530u, 52062u, 52586u, 53114u, 53650u,
    54188u, 54735u, 55289u, 55843u, 56403u,
}};

// Convenience: the largest K' in the table — RFC 6330 §5.1.2's
// K'_max constant. K' values larger than this are not supported.
inline constexpr std::uint32_t kKPrimeMax =
    kKPrimeTable[kKPrimeCount - 1];

}  // namespace LibFlute::rfc6330
