#!/usr/bin/env python3
# Copyright (C) Bitstem GmbH
# All rights reserved.
#
# This source code is proprietary and confidential.
# Unauthorized copying, distribution, or disclosure of this file,
# in whole or in part, is strictly prohibited unless explicitly
# permitted in writing by Bitstem GmbH.
#
# Author: Klaus Kuehnhammer <klaus@bitstem.com>

"""
Generate include/fec/rfc6330_kprime_table.h from RFC 6330 §5.6 Table 2.

libflute's RaptorFEC partitioner implements RFC 6330 §4.3 directly;
the §4.3 algorithm references KL(n) = "the maximum K' value in
Table 2 such that K' <= WS/(Al*ceil(T/(Al*n)))" — i.e. it needs
the list of supported K' values.

The codec (bitstem-fec) keeps the full Table 2 with all five
columns (K', J, S, H, W) in its private `src/generated/rq_tables.cpp`
behind `internal/` headers; that surface isn't reachable from a
binary-distribution consumer like libflute. We therefore ship our
own slice of Table 2 — just the K' column, 477 values — generated
from the same RFC source-of-truth so the data stays in sync.

Usage:
    python3 tools/gen_rfc6330_kprime_table.py [path/to/rfc6330.txt]

The default RFC path is tests/vectors/rfc6330.txt, which is checked
in alongside the rest of the spec-vector corpus. Pass an explicit
path to regenerate against a newer RFC text if it ever changes.

Output:
    include/fec/rfc6330_kprime_table.h
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROW_RE = re.compile(
    r"^\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|"
)


def extract_k_primes(rfc_text: str) -> list[int]:
    """Walk the RFC text and pull the first numeric column of every
    Table-2-shaped row (5 pipe-delimited integers). Returns the K'
    column."""
    primes: list[int] = []
    for line in rfc_text.splitlines():
        m = ROW_RE.match(line)
        if not m:
            continue
        primes.append(int(m.group(1)))
    return primes


def emit_header(primes: list[int], rfc_path: Path) -> str:
    rfc_sha = hashlib.sha256(rfc_path.read_bytes()).hexdigest()
    primes_csv = ",".join(str(p) for p in primes)
    primes_sha = hashlib.sha256(primes_csv.encode("ascii")).hexdigest()

    lines: list[str] = []
    a = lines.append
    a("/*  Copyright (C) Bitstem GmbH")
    a(" *  All rights reserved.")
    a(" *")
    a(" *  This source code is proprietary and confidential.")
    a(" *  Unauthorized copying, distribution, or disclosure of this file,")
    a(" *  in whole or in part, is strictly prohibited unless explicitly")
    a(" *  permitted in writing by Bitstem GmbH.")
    a(" *")
    a(" *  Author: Klaus Kuehnhammer <klaus@bitstem.com>")
    a(" */")
    a("")
    a("// GENERATED by tools/gen_rfc6330_kprime_table.py — do not edit by hand.")
    a("// Regenerate with `python3 tools/gen_rfc6330_kprime_table.py` after")
    a("// updating tests/vectors/rfc6330.txt.")
    a("//")
    a("// RFC 6330 §5.6 Table 2 — K' values, the supported source-block")
    a("// extended source-symbol counts. RFC 6330 §4.3 (Example Parameter")
    a("// Derivation Algorithm) needs these to compute KL(n), the maximum")
    a("// K' that fits the working-memory bound at sub-block count n.")
    a("// Encoder/decoder also use them to round K up to K' per §5.3.1 —")
    a("// that's the codec's concern, this header serves the partitioner.")
    a("//")
    a(f"// SHA-256 of the source RFC text:    {rfc_sha}")
    a(f"// SHA-256 of the comma-joined K's:   {primes_sha}")
    a("")
    a("#pragma once")
    a("")
    a("#include <array>")
    a("#include <cstddef>")
    a("#include <cstdint>")
    a("")
    a("namespace LibFlute::rfc6330 {")
    a("")
    a(f"inline constexpr std::size_t kKPrimeCount = {len(primes)};")
    a("")
    a("// Strictly increasing in the range [10, 56403].")
    a("inline constexpr std::array<std::uint32_t, kKPrimeCount> kKPrimeTable = {{")
    chunk = 8
    for i in range(0, len(primes), chunk):
        row = primes[i : i + chunk]
        a("    " + " ".join(f"{v}u," for v in row))
    a("}};")
    a("")
    a("// Convenience: the largest K' in the table — RFC 6330 §5.1.2's")
    a("// K'_max constant. K' values larger than this are not supported.")
    a("inline constexpr std::uint32_t kKPrimeMax =")
    a("    kKPrimeTable[kKPrimeCount - 1];")
    a("")
    a("}  // namespace LibFlute::rfc6330")
    a("")
    return "\n".join(lines)


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "rfc_path",
        nargs="?",
        type=Path,
        default=here / "tests" / "vectors" / "rfc6330.txt",
        help="path to the RFC 6330 plain-text source",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=here / "include" / "fec" / "rfc6330_kprime_table.h",
        help="generated header path",
    )
    args = parser.parse_args()

    if not args.rfc_path.exists():
        print(f"error: {args.rfc_path} not found", file=sys.stderr)
        return 1

    rfc_text = args.rfc_path.read_text(encoding="utf-8", errors="replace")
    primes = extract_k_primes(rfc_text)

    if len(primes) != 477:
        print(
            f"error: extracted {len(primes)} K' rows from {args.rfc_path}, "
            f"expected 477. Has the RFC text drifted?",
            file=sys.stderr,
        )
        return 1
    if primes != sorted(primes):
        print("error: extracted K' values are not strictly increasing.",
              file=sys.stderr)
        return 1
    if primes[0] != 10 or primes[-1] != 56403:
        print(
            f"error: K' range [{primes[0]}, {primes[-1]}] does not match "
            "the RFC 6330 §5.6 anchor range [10, 56403].",
            file=sys.stderr,
        )
        return 1

    header_text = emit_header(primes, args.rfc_path)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(header_text, encoding="utf-8")
    print(f"wrote {args.output} ({len(primes)} K' values)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
